## Seeds

# Users
User.create! :email => 'diegojrq@gmail.com', :email_confirmation => 'diegojrq@gmail.com', :first_name => "Diego", :last_name => "Queiroz", :birthday => "28/10/1987", :gender => "Male", :password => '12345678', :password_confirmation => '12345678'
User.create! :email => 'anap.aguiarc@gmail.com', :email_confirmation => 'anap.aguiarc@gmail.com', :first_name => "Ana", :birthday => "28/10/1987", :gender => "Female", :password => '12345678', :password_confirmation => '12345678'

# Accounts
Account.create! :name => 'Banco do Brasil', :user_id => 1, :start_value => 500
Account.create! :name => 'Santander', :user_id => 1, :start_value => 100
Account.create! :name => 'HSBC', :user_id => 1, :start_value => 0
Account.create! :name => 'Bradesco', :user_id => 2, :start_value => 0
Account.create! :name => 'Caixa Econômica', :user_id => 2, :start_value => 250

# Categories

Category.create! :name => "Caixa 1", :color => "250", :user_id => 1
Category.create! :name => "Caixa 2", :color => "250", :user_id => 1
Category.create! :name => "Caixa 3", :color => "250", :user_id => 2

# Transactions

# Currencies

Currency.create! :country => 'Albania', :name => 'Lek', :code => 'ALL', :symbol => 'Lek'
Currency.create! :country => 'Afghanistan', :name => 'Afghani', :code => 'AFN', :symbol => '؋'
Currency.create! :country => 'Argentina', :name => 'Peso', :code => 'ARS', :symbol => '$'
Currency.create! :country => 'Aruba', :name => 'Guilder', :code => 'AWG', :symbol => 'ƒ'
Currency.create! :country => 'Australia', :name => 'Dollar', :code => 'AUD', :symbol => '$'
Currency.create! :country => 'Azerbaijan', :name => 'Manat', :code => 'AZN', :symbol => 'ман'
Currency.create! :country => 'Bahamas', :name => 'Dollar', :code => 'BSD', :symbol => '$'
Currency.create! :country => 'Barbados', :name => 'Dollar', :code => 'BBD', :symbol => '$'
Currency.create! :country => 'Belarus', :name => 'Ruble', :code => 'BYR', :symbol => 'p.'
Currency.create! :country => 'Belize', :name => 'Dollar', :code => 'BZD', :symbol => 'BZ$'
Currency.create! :country => 'Bermuda', :name => 'Dollar', :code => 'BMD', :symbol => '$'
Currency.create! :country => 'Bolivia', :name => 'Boliviano', :code => 'BOB', :symbol => '$b'
Currency.create! :country => 'Bosnia and Herzegovina', :name => 'Convertible Marka', :code => 'BAM', :symbol => 'KM'
Currency.create! :country => 'Botswana', :name => 'Pula', :code => 'BWP', :symbol => 'P'
Currency.create! :country => 'Bulgaria', :name => 'Lev', :code => 'BGN', :symbol => 'лв'
Currency.create! :country => 'Brazil', :name => 'Real', :code => 'BRL', :symbol => 'R$'
Currency.create! :country => 'Brunei', :name => 'Darussalam Dollar', :code => 'BND', :symbol => '$'
Currency.create! :country => 'Cambodia', :name => 'Riel', :code => 'KHR', :symbol => '៛'
Currency.create! :country => 'Canada', :name => 'Dollar', :code => 'CAD', :symbol => '$'
Currency.create! :country => 'Cayman', :name => 'Dollar', :code => 'KYD', :symbol => '$'
Currency.create! :country => 'Chile', :name => 'Peso', :code => 'CLP', :symbol => '$'
Currency.create! :country => 'China', :name => 'Yuan Renminbi', :code => 'CNY', :symbol => '¥'
Currency.create! :country => 'Colombia', :name => 'Peso', :code => 'COP', :symbol => '$'
Currency.create! :country => 'Costa Rica', :name => 'Colon', :code => 'CRC', :symbol => '₡'
Currency.create! :country => 'Croatia', :name => 'Kuna', :code => 'HRK', :symbol => 'kn'
Currency.create! :country => 'Cuba', :name => 'Peso', :code => 'CUP', :symbol => '₱'
Currency.create! :country => 'Czech Republic', :name => 'Koruna', :code => 'CZK', :symbol => 'Kč'
Currency.create! :country => 'Denmark', :name => 'Krone', :code => 'DKK', :symbol => 'kr'
Currency.create! :country => 'Dominican Republic', :name => 'Peso', :code => 'DOP', :symbol => 'RD$'
Currency.create! :country => 'East Caribbean', :name => 'Dollar', :code => 'XCD', :symbol => '$'
Currency.create! :country => 'Egypt', :name => 'Pound', :code => 'EGP', :symbol => '£'
Currency.create! :country => 'El Salvador', :name => 'Colon', :code => 'SVC', :symbol => '$'
Currency.create! :country => 'Estonia', :name => 'Kroon', :code => 'EEK', :symbol => 'kr'
Currency.create! :country => 'Euro Member', :name => 'Euro', :code => 'EUR', :symbol => '€'
Currency.create! :country => 'Falkland Islands', :name => 'Pound', :code => 'FKP', :symbol => '£'
Currency.create! :country => 'Fiji', :name => 'Dollar', :code => 'FJD', :symbol => '$'
Currency.create! :country => 'Ghana', :name => 'Cedis', :code => 'GHC', :symbol => '¢'
Currency.create! :country => 'Gibraltar', :name => 'Pound', :code => 'GIP', :symbol => '£'
Currency.create! :country => 'Guatemala', :name => 'Quetzal', :code => 'GTQ', :symbol => 'Q'
Currency.create! :country => 'Guernsey', :name => 'Pound', :code => 'GGP', :symbol => '£'
Currency.create! :country => 'Guyana', :name => 'Dollar', :code => 'GYD', :symbol => '$'
Currency.create! :country => 'Honduras', :name => 'Lempira', :code => 'HNL', :symbol => 'L'
Currency.create! :country => 'Hong Kong', :name => 'Dollar', :code => 'HKD', :symbol => '$'
Currency.create! :country => 'Hungary', :name => 'Forint', :code => 'HUF', :symbol => 'Ft'
Currency.create! :country => 'Iceland', :name => 'Krona', :code => 'ISK', :symbol => 'kr'
Currency.create! :country => 'India', :name => 'Rupee', :code => 'INR', :symbol => '₹'
Currency.create! :country => 'Indonesia', :name => 'Rupiah', :code => 'IDR', :symbol => 'Rp'
Currency.create! :country => 'Iran', :name => 'Rial', :code => 'IRR', :symbol => '﷼'
Currency.create! :country => 'Isle of Man', :name => 'Pound', :code => 'IMP', :symbol => '£'
Currency.create! :country => 'Israel', :name => 'Shekel', :code => 'ILS', :symbol => '₪'
Currency.create! :country => 'Jamaica', :name => 'Dollar', :code => 'JMD', :symbol => 'J$'
Currency.create! :country => 'Japan', :name => 'Yen', :code => 'JPY', :symbol => '¥'
Currency.create! :country => 'Jersey', :name => 'Pound', :code => 'JEP', :symbol => '£'
Currency.create! :country => 'Kazakhstan', :name => 'Tenge', :code => 'KZT', :symbol => 'лв'
Currency.create! :country => 'Korea (North)', :name => 'Won', :code => 'KPW', :symbol => '₩'
Currency.create! :country => 'Korea (South)', :name => 'Won', :code => 'KRW', :symbol => '₩'
Currency.create! :country => 'Kyrgyzstan', :name => 'Som', :code => 'KGS', :symbol => 'лв'
Currency.create! :country => 'Laos', :name => 'Kip', :code => 'LAK', :symbol => '₭'
Currency.create! :country => 'Latvia', :name => 'Lat', :code => 'LVL', :symbol => 'Ls'
Currency.create! :country => 'Lebanon', :name => 'Pound', :code => 'LBP', :symbol => '£'
Currency.create! :country => 'Liberia', :name => 'Dollar', :code => 'LRD', :symbol => '$'
Currency.create! :country => 'Lithuania', :name => 'Litas', :code => 'LTL', :symbol => 'Lt'
Currency.create! :country => 'Macedonia', :name => 'Denar', :code => 'MKD', :symbol => 'ден'
Currency.create! :country => 'Malaysia', :name => 'Ringgit', :code => 'MYR', :symbol => 'RM'
Currency.create! :country => 'Mauritius', :name => 'Rupee', :code => 'MUR', :symbol => '₨'
Currency.create! :country => 'Mexico', :name => 'Peso', :code => 'MXN', :symbol => '$'
Currency.create! :country => 'Mongolia', :name => 'Tughrik', :code => 'MNT', :symbol => '₮'
Currency.create! :country => 'Mozambique', :name => 'Metical', :code => 'MZN', :symbol => 'MT'
Currency.create! :country => 'Namibia', :name => 'Dollar', :code => 'NAD', :symbol => '$'
Currency.create! :country => 'Nepal', :name => 'Rupee', :code => 'NPR', :symbol => '₨'
Currency.create! :country => 'Netherlands', :name => 'Antilles Guilder', :code => 'ANG', :symbol => 'ƒ'
Currency.create! :country => 'New Zealand', :name => 'Dollar', :code => 'NZD', :symbol => '$'
Currency.create! :country => 'Nicaragua', :name => 'Cordoba', :code => 'NIO', :symbol => 'C$'
Currency.create! :country => 'Nigeria', :name => 'Naira', :code => 'NGN', :symbol => '₦'
Currency.create! :country => 'Norway', :name => 'Krone', :code => 'NOK', :symbol => 'kr'
Currency.create! :country => 'Oman', :name => 'Rial', :code => 'OMR', :symbol => '﷼'
Currency.create! :country => 'Pakistan', :name => 'Rupee', :code => 'PKR', :symbol => '₨'
Currency.create! :country => 'Panama', :name => 'Balboa', :code => 'PAB', :symbol => 'B/.'
Currency.create! :country => 'Paraguay', :name => 'Guarani', :code => 'PYG', :symbol => 'Gs'
Currency.create! :country => 'Peru', :name => 'Nuevo Sol', :code => 'PEN', :symbol => 'S/.'
Currency.create! :country => 'Philippines', :name => 'Peso', :code => 'PHP', :symbol => '₱'
Currency.create! :country => 'Poland', :name => 'Zloty', :code => 'PLN', :symbol => 'zł'
Currency.create! :country => 'Qatar', :name => 'Riyal', :code => 'QAR', :symbol => '﷼'
Currency.create! :country => 'Romania', :name => 'New Leu', :code => 'RON', :symbol => 'lei'
Currency.create! :country => 'Russia', :name => 'Ruble', :code => 'RUB', :symbol => 'руб'
Currency.create! :country => 'Saint Helena', :name => 'Pound', :code => 'SHP', :symbol => '£'
Currency.create! :country => 'Saudi Arabia', :name => 'Riyal', :code => 'SAR', :symbol => '﷼'
Currency.create! :country => 'Serbia', :name => 'Dinar', :code => 'RSD', :symbol => 'Дин.'
Currency.create! :country => 'Seychelles', :name => 'Rupee', :code => 'SCR', :symbol => '₨'
Currency.create! :country => 'Singapore', :name => 'Dollar', :code => 'SGD', :symbol => '$'
Currency.create! :country => 'Solomon Islands', :name => 'Dollar', :code => 'SBD', :symbol => '$'
Currency.create! :country => 'Somalia', :name => 'Shilling', :code => 'SOS', :symbol => 'S'
Currency.create! :country => 'South Africa', :name => 'Rand', :code => 'ZAR', :symbol => 'S'
Currency.create! :country => 'Sri Lanka', :name => 'Rupee', :code => 'LKR', :symbol => '₨'
Currency.create! :country => 'Sweden', :name => 'Krona', :code => 'SEK', :symbol => 'kr'
Currency.create! :country => 'Switzerland', :name => 'Franc', :code => 'CHF', :symbol => 'CHF'
Currency.create! :country => 'Suriname', :name => 'Dollar', :code => 'SRD', :symbol => '$'
Currency.create! :country => 'Syria', :name => 'Pound', :code => 'SYP', :symbol => '£'
Currency.create! :country => 'Taiwan', :name => 'New Dollar', :code => 'TWD', :symbol => 'NT$'
Currency.create! :country => 'Thailand', :name => 'Baht', :code => 'THB', :symbol => '฿'
Currency.create! :country => 'Trinidad and Tobago', :name => 'Dollar', :code => 'TTD', :symbol => 'TT$'
Currency.create! :country => 'Turkey', :name => 'Lira', :code => 'TRL', :symbol => '₤'
Currency.create! :country => 'Tuvalu', :name => 'Dollar', :code => 'TVD', :symbol => '$'
Currency.create! :country => 'Ukraine', :name => 'Hryvna', :code => 'UAH', :symbol => '₴'
Currency.create! :country => 'United Kingdom', :name => 'Pound', :code => 'GBP', :symbol => '£'
Currency.create! :country => 'United States', :name => 'Dollar', :code => 'USD', :symbol => '$'
Currency.create! :country => 'Uruguay', :name => 'Peso', :code => 'UYU', :symbol => '$U'
Currency.create! :country => 'Uzbekistan', :name => 'Som', :code => 'UZS', :symbol => 'лв'
Currency.create! :country => 'Venezuela', :name => 'Bolivar Fuerte', :code => 'VEF', :symbol => 'Bs'
Currency.create! :country => 'Viet Nam', :name => 'Dong', :code => 'VND', :symbol => '₫'
Currency.create! :country => 'Yemen', :name => 'Rial', :code => 'YER', :symbol => '﷼'
Currency.create! :country => 'Zimbabwe', :name => 'Dollar', :code => 'ZWD', :symbol => 'Z$'